import App from './App.vue';
import { createApp } from 'vue';
import 'vant/lib/index.css';
import vant from 'vant';
import router from './router/index.ts';
import { createPinia } from 'pinia';
const pinia = createPinia();
const app = createApp(App);
app.use(pinia);
app.use(vant);
app.use(router);
app.mount('#app');
